### ISSUE TITLE
there is an error during yarn dev

### ISSUE THREAD

**Issue by selectbook** [openshiporg/openship#16]
the error log is bellow:

yarn run v1.22.21
$ yarn migrate && next dev
$ keystone prisma migrate deploy
Your Prisma and GraphQL schemas are not up to date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Comment by junaid33** [comment]
Have you taken the latest pull? The prisma schema had been changed and the file not updated. It seems to be working for me locally with a fresh pull.

**Comment by selectbook** [comment]
This error occurred because I forgot to replace DATABASE_URL with my postgres connection string
I have replaced, but there is another error:

```
yarn run v1.22.21
$ yarn migrate && next dev
$ keystone prisma migrate deploy
error Command failed with exit code 1.t up to date
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```



> Have you taken the latest pull? The prisma schema had been changed and the file not updated. It seems to be working for me locally with a fresh pull.

**Comment by junaid33** [comment]
Hmmm... looks like the migration is not being applied to the database. Do you have the specific log and error? What is your Node version? Openship needed a dependency that still uses Node 18 so Node 20 doesn't work just yet. Also, please verify your postgres database URL and make sure the table is empty.

**Comment by selectbook** [comment]
> Hmmm... looks like the migration is not being applied to the database. Do you have the specific log and error? What is your Node version? Openship needed a dependency that still uses Node 18 so Node 20 doesn't work just yet. Also, please verify your postgres database URL and make sure the table is empty.

all logs are:
`D:\project\openship>yarn dev
yarn run v1.22.21
$ yarn migrate && next dev
$ keystone prisma migrate deploy
Your Prisma and GraphQL schemas are not up to date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\project\openship>node -v
v18.19.0

D:\project\openship>`

And the node version is 18.19.0. The database DATABASE_URL is DATABASE_URL=postgresql://root:Le@20230823@127.0.0.1:5432/openship
Is thre anything wrong?

**Comment by selectbook** [comment]
> Hmmm... looks like the migration is not being applied to the database. Do you have the specific log and error? What is your Node version? Openship needed a dependency that still uses Node 18 so Node 20 doesn't work just yet. Also, please verify your postgres database URL and make sure the table is empty.

all logs are:

```
D:\project\openship>yarn dev
yarn run v1.22.21
$ yarn migrate && next dev
$ keystone prisma migrate deploy
Your Prisma and GraphQL schemas are not up to date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\project\openship>node -v
v18.19.0

D:\project\openship>
```

And the node version is 18.19.0. The database DATABASE_URL is `DATABASE_URL=postgresql://root:Le@20230823@127.0.0.1:5432/openship`
Is thre anything wrong?

**Comment by junaid33** [comment]
I'm using yarn run v1.22.4. Could you update yarn to that version and try? Also, can you try with a online hosted postgres database? https://neon.tech/ lets you get a free database. Maybe you can try using that URI string with yarn dev. Also, I'm on Node 18.18.2 but don't think that should be an issue.

**Comment by selectbook** [comment]
ok, solved. It's because the DATABASE_URL is wrong.
