### ISSUE TITLE
How long should the railway build take?

### ISSUE THREAD

**Issue by duttaoindril** [openshiporg/openship#5]
![image](https://user-images.githubusercontent.com/4969854/197115122-9b1d3218-132d-4908-b814-cb335cbce1df.png)

It's been running for over an hour and 20 mins.

**Comment by junaid33** [comment]
Should take 4-5 minutes max. Looks like it got stuck performing the migrations. Can you check the Postgres DB to see if the tables have been created? Also under the service settings, can you see which builder you’re using? Default is Nixpacks but that has been buggy for me so I would try Heroku Buildpacks.

**Comment by duttaoindril** [comment]
I just retried with the exact same config and it worked that time 🤷‍♂️
